zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      serviceId: stdstack-auth-server
    course-api:
      path: /courses/**
      serviceId: stdstack-course-service
  retryable: true
  ignored-services: "*"
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

security:
  oauth2:
    resource:
      jwt:
        key-value: 123

eureka:
  client:
    serviceUrl:
      defaultUrl: http://stdstack-eureka-server:8761/eureka/
      defaultZone: http://stdstack-eureka-server:8761/eureka/

spring:
  application:
    name: stdstack-gateway-zuul